spring.application.name=extendboard

# createDatabaseIfNotExist=true ?? ??!
spring.datasource.url=jdbc:mysql://localhost:3306/extendboard_db?createDatabaseIfNotExist=true&serverTimezone=UTC&characterEncoding=UTF-8

spring.datasource.username=root
spring.datasource.password=147200

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true